[versions]
agp = "8.13.2"
appcompat = "1.7.1"
assertjCore = "3.27.6"
collectionKtx = "1.5.0"
coreKtx = "1.17.0"
coreSplashscreen = "1.2.0"
espressoCore = "3.7.0"
graphview = "4.2.2"
junit = "4.13.2"
junitToolbox = "2.4"
junitVersion = "1.3.0"
kotlin = "2.2.21"
ktlint = "14.0.1"
lifecycleViewmodelKtx = "2.10.0"
material = "1.13.0"
media = "1.7.1"
mockitoCore = "5.21.0"
mockitoKotlin = "6.1.0"
preferenceKtx = "1.2.1"
robolectric = "4.16"
rules = "1.7.0"
slf4jSimple = "2.0.17"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-collection-ktx = { group = "androidx.collection", name = "collection-ktx", version.ref = "collectionKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espressoCore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitVersion" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertjCore" }
graphview = { group = "com.jjoe64", name = "graphview", version.ref = "graphview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-toolbox = { group = "com.googlecode.junit-toolbox", name = "junit-toolbox", version.ref = "junitToolbox" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4jSimple" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
